project_id = "vkjrqirvdvjbemsfzxof"

[functions."push-broadcast"]
verify_jwt = false

[functions."webpush-admin-broadcast"]
verify_jwt = false
<<<<<<< HEAD

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_autoconfirm = true
enable_phone_confirmations = false
enable_phone_autoconfirm = true

[functions.webpush-send]
verify_jwt = false

[functions.webpush-upsert]
verify_jwt = false
=======
>>>>>>> 18c0d0c8 (Fix: SW copy, functions and vite config for push)
