project_id = "vkjrqirvdvjbemsfzxof"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[functions]
verify_jwt = true

[functions.fcm-test]
verify_jwt = false

[functions.fcm-send]
verify_jwt = false

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_autoconfirm = true
enable_phone_confirmations = false
enable_phone_autoconfirm = true

[functions.webpush-send]
verify_jwt = false

[functions.webpush-upsert]
verify_jwt = false

[functions.geofence-engine]
verify_jwt = false

[functions.mirror-push-log-harvester]
verify_jwt = false

[functions.webpush-admin-broadcast]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-mode]
verify_jwt = false

[functions.create-random-markers]
verify_jwt = false

[functions.feed-crawler]
verify_jwt = false

[functions.notifier-engine]
verify_jwt = false

[functions.handle-buzz-press]
verify_jwt = true

[functions.handle-buzz-payment-success]
verify_jwt = true

[functions.handle-buzz-map]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.reset-mission]
verify_jwt = false

[functions.create_qr_code]
verify_jwt = false

[functions.ensure-agent-code]
verify_jwt = false

[functions.generate-mission-clues]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-norah-context]
verify_jwt = true

[functions.get-user-state]
verify_jwt = true

[functions.get-nearby-prizes]
verify_jwt = true

[functions.rag-search]
verify_jwt = true

[functions.open-support-ticket]
verify_jwt = true

[functions.populate-knowledge-base]
verify_jwt = false

[functions.norah-chat]
verify_jwt = false