name = "m1ssion"                 # <- obbligatorio per Pages
pages_build_output_dir = "dist"  # <- cartella build

# (opzionale) headers per SW/PWA:
# [[headers]]
# for = "/*"
# [headers.values]
# Cache-Control = "public, max-age=0, must-revalidate"
