# © 2025 M1SSION™ NIYVORA KFT – Joseph MULÉ
# Cloudflare Pages configuration for M1SSION™ PWA

name = "m1ssion-pwa"
pages_build_output_dir = "dist"

[env.production]
compatibility_date = "2023-12-01"

[[env.production.routes]]
pattern = "m1ssion.eu/*"
custom_domain = true

[[env.production.routes]]
pattern = "*.m1ssion-pwa.pages.dev/*"

# SPA fallback configuration
[build]
command = "npm run build"
cwd = "."