# © 2025 Joseph MULÉ – M1SSION™ – ALL RIGHTS RESERVED – NIYVORA KFT™
name: Set Supabase Stripe Secrets
on:
  workflow_dispatch:
    inputs:
      STRIPE_PUBLISHABLE_KEY:
        description: 'pk_live_*'
        required: true
      STRIPE_SECRET_KEY:
        description: 'sk_live_*'
        required: true
jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://cli.supabase.com/install/linux | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH
      - name: Login & Link
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref "${{ secrets.PROJECT_REF }}"
      - name: Set Secrets
        run: |
          supabase secrets set \
            STRIPE_PUBLISHABLE_KEY="${{ inputs.STRIPE_PUBLISHABLE_KEY }}" \
            STRIPE_SECRET_KEY="${{ inputs.STRIPE_SECRET_KEY }}"